uploads = []
generated = []

[[outputs]]
id = "TullRvxsy88I00MJXnj3b"
uri = "file://ethiomark-bingo.tar.gz"
type = "unspecified"
title = "Ethiomark Bingo — Project Files (tar.gz)"

[[outputs]]
id = "Harj4u28QIjBYLEAaAetr"
uri = "file://ethiomark-bingo-full.tar.gz"
type = "unspecified"
title = "Ethiomark Bingo — Complete Project (all files, 4.4 MB)"
